development:
  adapter: postgresql
  encoding: unicode
  database: pos_development
  pool: 5
  username: lairdd
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: foo_test
  pool: 5
  username: lairdd
  password:
  host: localhost
  port: 5432
